parameters:
  environment: 'nuget production'
  projects: ''

jobs:
- ${{ each project in parameters.projects }}:
  - deployment: '${{ project.jobId }}'
    displayName: 'nuget push: ${{ project.projectName }}'
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: NuGetCommand@2
              inputs:
                command: 'push'
                packagesToPush: '$(Agent.BuildDirectory)/**/*.nupkg;!$(Agent.BuildDirectory)/**/*.symbols.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'lonesomegeek'
                verbosityPush: 'Normal'