# trigger:
# - master

stages:
- stage: 'build'
  displayName: build   
  
  jobs:
  - template: pipeline-templates/build.yml
    parameters:
      project-name: "LSG.GenericCrud"
      configuration: "Release"
  - template: pipeline-templates/build.yml
    parameters:
      project-name: "LSG.GenericCrud.Dto"
      configuration: "Release"
- stage: 'deployment'
  dependsOn: 'build'
  jobs:
  - template: pipeline-templates/release.yml