# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'LSG.GenericCrud - dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)
      projects: 'LSG.GenericCrud/*.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: 'LSG.GenericCrud.Dto - dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)
      projects: 'LSG.GenericCrud.Dto/*.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack $(buildConfiguration)'
    inputs:
      command: 'pack'
      packagesToPack: 'LSG.GenericCrud/*.csproj'
      # versioningScheme: 'byBuildNumber'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
