# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  
steps:
  - task: DotNetCoreCLI@2
    displayName: 'LSG.GenericCrud - dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: 'LSG.GenericCrud/*.csproj'
      arguments: '-c $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'LSG.GenericCrud.Dto - dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: 'LSG.GenericCrud.Dto/*.csproj'
      arguments: '-c $(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'lonesomegeek'
      
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'lonesomegeek'